import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:bersih_in/app/core/constants/app_strings.dart';
import 'package:bersih_in/app/core/services/user_session_service.dart';
import 'package:bersih_in/app/routes/app_routes.dart';
import 'package:bersih_in/app/features/booking/data/models/order_model.dart';
import 'package:bersih_in/app/features/booking/data/models/price_estimate_model.dart';
import 'package:bersih_in/app/features/booking/data/repositories/order_repository.dart';

class BookingController extends GetxController {
  final OrderRepository _orderRepository = OrderRepository();

  // Booking form state
  final roomSizeM2 = 10.0.obs;
  final selectedExtras = <String>[].obs;
  final isLoading = false.obs;

  // Price estimate (set after AI camera flow)
  Rxn<PriceEstimateModel> priceEstimate = Rxn<PriceEstimateModel>();

  void setRoomSize(double v) => roomSizeM2.value = v;

  void toggleExtra(String e) {
    if (selectedExtras.contains(e)) {
      selectedExtras.remove(e);
    } else {
      selectedExtras.add(e);
    }
  }

  /// Validates booking form and navigates to AI Camera
  Future<void> proceedToCamera() async {
    Get.toNamed(
      AppRoutes.AI_CAMERA,
      arguments: {
        'roomSize': roomSizeM2.value,
        'extras': selectedExtras.toList(),
      },
    );
  }

  /// Called when coming back from price estimation
  void setPriceEstimate(PriceEstimateModel estimate) {
    priceEstimate.value = estimate;
  }

  /// Submit final order to Firestore
  Future<void> submitOrder() async {
    final estimate = priceEstimate.value;
    if (estimate == null) return;

    final userSession = Get.find<UserSessionService>();
    if (userSession.currentUser.value == null) return;

    isLoading.value = true;
    try {
      final now = DateTime.now();
      final order = OrderModel(
        orderId: '', // will be auto-generated by Firestore
        userId: userSession.currentUser.value!.uid,
        roomSizeM2: estimate.roomSizeM2,
        dirtLevel: estimate.dirtLevel,
        dirtLevelIndex: estimate.dirtLevelIndex,
        extras: estimate.extras,
        estimatedPrice: estimate.estimatedPrice,
        estimatedMinutes: estimate.estimatedMinutes,
        status: 'pending',
        partnerName: 'Siti Rahayu',
        partnerVerified: true,
        createdAt: now,
        updatedAt: now,
      );

      await _orderRepository.createOrder(order);

      Get.snackbar(
        'Berhasil',
        AppStrings.orderSuccess,
        snackPosition: SnackPosition.BOTTOM,
        backgroundColor: const Color(0xFF27AE60),
        colorText: Colors.white,
      );

      // Reset state
      roomSizeM2.value = 10.0;
      selectedExtras.clear();
      priceEstimate.value = null;

      Get.offAllNamed(AppRoutes.HOME);
    } catch (e) {
      Get.snackbar(
        'Error',
        AppStrings.errorGeneral,
        snackPosition: SnackPosition.BOTTOM,
        backgroundColor: const Color(0xFFE74C3C),
        colorText: Colors.white,
      );
    } finally {
      isLoading.value = false;
    }
  }
}
